name: Continuous Integration

on: 
  push:
   branches:
    - master
  pull_request:

jobs:
  automerge:
    name: Merge dependabot's PRs
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
